stdinfosys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("webapp.urls", namespace="webapp")),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from . import views
app_name = "app_webapp"
urlpatterns = [
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("discussion/", views.DiscussionView.as_view(), name="discussion"),
    path("assignment/create/<int:pk>/",views.AssignmentCreateView.as_view(), name="create_assignment"),
    path("assignments/",views.AssignmentView.as_view(), name="assignment"),
    path("attendence/",views.AttendenceView.as_view(), name="attendence"),
    path("events/",views.EventView.as_view(),name="event"),

    path("", views.HomeView.as_view(), name="dashboard"),
]

webapp/models/college.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.contrib.humanize.templatetags.humanize import ordinal
from .. import validators
from .. import utils
from .essentials import EventManager, AssignmentManager
USER = get_user_model()
DEPARTMENT_CHOICES = (
    ("csit", "BSc Computer Science and Information Technology"),
    ("bca", "Bachelor of Computer Application"),
    ("coer", "Computer Engineering"),
    ("eer", "Electrical Engineering"),
    ("mer", "Mechanical Engineering"),
    ("cer", "Civil Engineering")
)
STATUS_CHOICES = (
    (
        ("p", "Pending"),
        ("c", "Checked"),
        ("r", "Rejected"),
    )
)
DAYS_OF_WEEK = (
    ("sun", "Sunday"),
    ("mon", "Monday"),
    ("tue", "Tuesday"),
    ("wed", "Wednesday"),
    ("thu", "Thursday"),
    ("fri", "Friday")
)
ATTENDENCE_STATUS = (
    (
        "p", "Present"
    ),
    (
        "a", "Absent"
    )
)


class College(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    website = models.URLField()
    logo = models.ImageField(upload_to="images/logo/", null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.id = 1
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "College"


class Department(models.Model):
    name = models.CharField(choices=DEPARTMENT_CHOICES,
                            max_length=4, db_index=True)
    hod = models.OneToOneField(USER, on_delete=models.SET_NULL,
                               related_name="department", related_query_name="has_department", null=True,
                               validators=[validators.validate_teacher, ])

    def __str__(self):
        return f"Department of {self.get_name_display()}"


class Semester(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE,
                                   related_name="semester", related_query_name="has_semester")
    year = models.IntegerField(
        validators=[validators.validate_year, ], db_index=True)
    room = models.CharField(max_length=5, db_index=True)
    cr = models.OneToOneField(USER, on_delete=models.SET_NULL,
                              related_name="+", null=True, related_query_name="+", validators=[validators.validate_student, ]
                              )

    def __str__(self):
        return f"{self.department.get_name_display()} - {ordinal(timezone.now().date().year - self.year + 1)} year"


class Routine(models.Model):
    teacher = models.ForeignKey(USER, on_delete=models.CASCADE,
                                related_name="routine", related_query_name="has_routine")
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE,
                                 related_name="routine", related_query_name="has_routine")
    starts = models.TimeField()
    ends = models.TimeField()
    day_of_week = models.CharField(
        choices=DAYS_OF_WEEK, max_length=3, db_index=True)
    created_at = models.DateField(default=timezone.now, editable=False)
    updated_at = models.DateField(default=timezone.now, editable=False)

    def save(self, *args, **kwargs):
        self.updated_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.semester} - {self.get_day_of_week_display()}"

    class Meta:
        ordering = ("starts",)


class Attendence(models.Model):
    routine = models.ForeignKey(Routine, on_delete=models.SET_NULL,
                                related_name="attendence", related_query_name="has_attendence", null=True, db_index=True)
    student = models.ForeignKey(USER, on_delete=models.CASCADE,
                                related_name='attendence', related_query_name="has_attendence", db_index=True)
    status = models.CharField(choices=ATTENDENCE_STATUS, max_length=1)
    date = models.DateField(default=timezone.now,
                            editable=False, db_index=True)

    class Meta:
        ordering = ("-date",)

    def __str__(self):
        return f"{self.student.get_full_name()} {'is' if self.date == timezone.now().date() else 'was'} {self.get_status_display()} on {self.date}"


class Assignment(models.Model):
    topic = models.CharField(max_length=100, db_index=True)
    semester = models.ForeignKey(Semester,
                                 on_delete=models.CASCADE,
                                 related_name="assignment",
                                 related_query_name="has_assignment")
    image = models.ImageField(
        upload_to=utils.upload_directory_path, null=True, blank=True)
    description = models.TextField(null=True)
    upload = models.FileField(
        upload_to=utils.upload_directory_path, null=True, blank=True)
    teacher = models.ForeignKey(
        USER, on_delete=models.CASCADE, related_name="+", related_query_name="+", validators=[validators.validate_teacher, ])
    objects = AssignmentManager()
    due_date = models.DateField(db_index=True)
    assigned_at = models.DateField(default=timezone.now, editable=False)

    def __str__(self):
        return self.topic

    class Meta:
        ordering = ("due_date",)
        constraints = [
            models.UniqueConstraint(
                "topic", "semester", "teacher", name="unique_semester_topic_teacher"),
        ]


class Submission(models.Model):
    student = models.ForeignKey(USER, on_delete=models.CASCADE, validators=[
                                validators.validate_student, ], related_name="submission", related_query_name="has_submission")
    upload = models.FileField(
        upload_to="assignments/%Y-%m-%d", null=True, blank=True)
    answer = models.TextField(null=True, blank=True)
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE,
                                   related_name="submission", related_query_name="has_submission")
    status = models.CharField(choices=STATUS_CHOICES,
                              max_length=1, default="p")

    submitted_at = models.DateField(default=timezone.now, editable=False)

    class Meta:
        ordering = ("submitted_at",)


class Event(models.Model):
    topic = models.CharField(max_length=100)
    image = models.ImageField(upload_to="images/events/%Y-%m-%d")
    description = models.TextField()
    happening = models.DateTimeField()
    added_at = models.DateTimeField(default=timezone.now, editable=False)
    objects = EventManager()

    def __str__(self):
        return self.topic
    class Meta:
        ordering = ("happening",)


class Club(models.Model):
    name = models.CharField(max_length=100)
    facebook_url = models.URLField(null=True, blank=True)
    instagram_url = models.URLField(null=True, blank=True)
    discord_url = models.URLField(null=True, blank=True)
    linkedin_url = models.URLField(null=True, blank=True)
    president = models.OneToOneField(
        USER, on_delete=models.CASCADE, related_name="+", related_query_name="+")
    members = models.ManyToManyField(
        USER, related_name="club", related_query_name="has_club")

    def __str__(self):
        return self.name


class Discussion(models.Model):
    user = models.ForeignKey(USER, on_delete=models.CASCADE,
                             related_name="discussion", related_query_name="has_discussion")
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE,
                                 related_name="discussion", related_query_name="has_discussion")
    message = models.TextField()
    discussed_at = models.DateTimeField(default=timezone.now, editable=False)

    class Meta:
        ordering = ("discussed_at",)

webapp/models/essentials.py
from django.db import models
from django.utils import timezone


class AssignmentQuerySet(models.QuerySet):
    def get_upcoming(self):
        return self.filter(due_date__gte=timezone.now())

    def get_due_today(self):
        return self.filter(due_date=timezone.now())


class AssignmentManager(models.Manager):
    def get_queryset(self):
        return AssignmentQuerySet(self.model)


class EventQuerySet(models.QuerySet):
    def get_upcoming(self):
        return self.filter(happening__gte=timezone.now())

    def get_happening_today(self):
        return self.filter(happening=timezone.now())


class EventManager(models.Model):
    def get_queryset(self):
        return EventQuerySet(self.model)

webapp/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
USER = get_user_model()
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = USER
        fields = ('email', 'username',)
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = USER
        fields = ('email', 'username',)

webapp/views.py
from ast import Sub
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView, list, detail
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.shortcuts import redirect
from .models import Discussion, Assignment, Submission, Event
from django.db.models import Q


class Login(UserPassesTestMixin, LoginView):
    template_name = "webapp/login.html"

    def test_func(self):
        return not self.request.user.is_authenticated

    def handle_no_permission(self):
        return redirect(reverse("app_webapp:dashboard"))


class Logout(LoginRequiredMixin, LogoutView):
    pass


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "webapp/index.html"

    def get(self, request, *args, **kwargs):
        today = timezone.now().date().strftime("%a").lower()
        today = "sun" if today == "sat" else today
        user = request.user
        if not user.is_teacher:
            context = {
                "routines": user.semester.routine.filter(day_of_week=today),
                "events":Event.objects.filter(happening__date=timezone.now()),
                "remaining_assignments": user.semester.assignment.all().get_upcoming()

            }
        else:
            context = {
                "routines": user.routine.filter(day_of_week=today),
                "assignments": Submission.objects.filter(assignment__teacher=user, status="p")
            }
            self.template_name = "webapp/teacher_index.html"
        return render(request, self.template_name, context)


class AssignmentView(LoginRequiredMixin, list.ListView):
    model = Assignment
    template_name = "webapp/assignment.html"
    context_object_name = "assignments"

    def get_queryset(self):
        return super().get_queryset().filter(semester=self.request.user.semester)


class AssignmentCreateView(LoginRequiredMixin, CreateView):
    model = Submission
    template_name = "webapp/homework.html"
    fields = ("assignment",)
    success_url = reverse_lazy("app_webapp:assignment")

    def get(self, request, pk):
        return render(request, self.template_name, {"assignment": Assignment.objects.get(id=pk)})

    def form_valid(self, form):
        form.instance.student = self.request.user
        return super().form_valid(form)


class DiscussionView(LoginRequiredMixin, CreateView):
    template_name = "webapp/discussion.html"
    model = Discussion
    fields = ("message",)
    success_url = reverse_lazy("app_webapp:discussion")

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {"discussions": self.request.user.semester.discussion.all()[:20]})

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.semester = self.request.user.semester
        return super().form_valid(form)


class EventView(LoginRequiredMixin, list.ListView):
    template_name = "webapp/events.html"
    model = Event
    context_object_name = "events"

    def get_queryset(self):
        return super().get_queryset().filter(happening__date__gte=timezone.now())

class AttendenceView(LoginRequiredMixin,TemplateView):
    template_name = "webapp/attendence.html"

webapp/templates/webapp/_sidebar.html
{% load static %}
<div class="flex flex-col py-8 pl-6 pr-2 w-64 bg-white flex-shrink-0">
    <aside class="fixed inset-y-0 left-0 bg-white shadow-md max-h-screen w-60">
        <div class="flex flex-col justify-between h-full">
            <div class="flex-grow">
                <div class="px-4 py-6 text-center border-b">
                    <img class="w-20 h-20 rounded-full ring-2 ring-blue-500 dark:ring-blue-500"
                        src="{{user.profile|default:'/static/webapp/images/shailesh.png'}}" alt="Large avatar" />
                </div>
                <div class="p-4">
                    <ul class="space-y-1">
                        <li>
                            <a href="{% url 'app_webapp:dashboard' %}"
                                class="flex bg-white  {% if current == 'dash' %}bg-blue-200 text-yellow-900{% endif %} rounded-xl font-bold text-sm py-3 px-4">
                                <svg xmlns="http://www.w3.org/2000/svg" class="text-lg mr-4" width="1.3em"
                                    height="1.3em" viewBox="2 0 24 24" stroke-width="5" stroke="currentColor"
                                    fill="none" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                </svg>

                                Dashboard
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'app_webapp:attendence' %}"
                                class="flex bg-white  {% if current == 'atten' %}bg-blue-200 text-yellow-900{% endif %} rounded-xl font-bold text-sm py-3 px-4">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                                    class="text-lg mr-4" viewBox="0 0 16 16">
                                    <path
                                        d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM5 4h6a.5.5 0 0 1 0 1H5a.5.5 0 0 1 0-1zm-.5 2.5A.5.5 0 0 1 5 6h6a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5zM5 8h6a.5.5 0 0 1 0 1H5a.5.5 0 0 1 0-1zm0 2h3a.5.5 0 0 1 0 1H5a.5.5 0 0 1 0-1z" />
                                </svg>Attendence
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'app_webapp:assignment' %}"
                                class="flex bg-white  {% if current == 'assign' %}bg-blue-200 text-yellow-900{% endif %} rounded-xl font-bold text-sm py-3 px-4"">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                                    class="text-lg mr-4" viewBox="0 0 16 16">
                                    <path
                                        d="M9.828 3h3.982a2 2 0 0 1 1.992 2.181l-.637 7A2 2 0 0 1 13.174 14H2.825a2 2 0 0 1-1.991-1.819l-.637-7a1.99 1.99 0 0 1 .342-1.31L.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 2 0 0 0 9.828 3zm-8.322.12C1.72 3.042 1.95 3 2.19 3h5.396l-.707-.707A1 1 0 0 0 6.172 2H2.5a1 1 0 0 0-1 .981l.006.139z" />
                                </svg>Assignments
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'app_webapp:discussion' %}"
                                class="flex bg-white  {% if current == 'disc' %}bg-blue-200 text-yellow-900{% endif %} rounded-xl font-bold text-sm py-3 px-4"">
                                <svg xmlns="http://www.w3.org/2000/svg" class="text-lg mr-4" width="1.2em"
                                    height="1.2em" viewBox="2 0 24 24" stroke-width="2.4" stroke="currentColor"
                                    fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" />
                                    <path d="M4 21v-13a3 3 0 0 1 3 -3h10a3 3 0 0 1 3 3v6a3 3 0 0 1 -3 3h-9l-4 4" />
                                    <line x1="8" y1="9" x2="16" y2="9" />
                                    <line x1="8" y1="13" x2="14" y2="13" />
                                </svg>
                                Discussion
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'app_webapp:event' %}"
                                class="flex bg-white  {% if current == 'events' %}bg-blue-200 text-yellow-900{% endif %} rounded-xl font-bold text-sm py-3 px-4">
                                <svg class="text-lg mr-4" width="1.2em" height="1.2em" viewBox="2 0 24 24"
                                    stroke-width="2.4" stroke="currentColor" fill="none" stroke="currentColor"
                                    stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                    <path
                                        d="M14.5 10c-.83 0-1.5-.67-1.5-1.5v-5c0-.83.67-1.5 1.5-1.5s1.5.67 1.5 1.5v5c0 .83-.67 1.5-1.5 1.5z" />
                                    <path d="M20.5 10H19V8.5c0-.83.67-1.5 1.5-1.5s1.5.67 1.5 1.5-.67 1.5-1.5 1.5z" />
                                    <path
                                        d="M9.5 14c.83 0 1.5.67 1.5 1.5v5c0 .83-.67 1.5-1.5 1.5S8 21.33 8 20.5v-5c0-.83.67-1.5 1.5-1.5z" />
                                    <path d="M3.5 14H5v1.5c0 .83-.67 1.5-1.5 1.5S2 16.33 2 15.5 2.67 14 3.5 14z" />
                                    <path
                                        d="M14 14.5c0-.83.67-1.5 1.5-1.5h5c.83 0 1.5.67 1.5 1.5s-.67 1.5-1.5 1.5h-5c-.83 0-1.5-.67-1.5-1.5z" />
                                    <path d="M15.5 19H14v1.5c0 .83.67 1.5 1.5 1.5s1.5-.67 1.5-1.5-.67-1.5-1.5-1.5z" />
                                    <path
                                        d="M10 9.5C10 8.67 9.33 8 8.5 8h-5C2.67 8 2 8.67 2 9.5S2.67 11 3.5 11h5c.83 0 1.5-.67 1.5-1.5z" />
                                    <path d="M8.5 5H10V3.5C10 2.67 9.33 2 8.5 2S7 2.67 7 3.5 7.67 5 8.5 5z" />
                                </svg>
                                Events
                            </a>
                        </li>
                        <li>
                            <a href="javascript:void(0)"
                                class="flex bg-white  {% if current == 'notes' %}bg-blue-200 text-yellow-900{% endif %} rounded-xl font-bold text-sm py-3 px-4">
                                <svg class="text-lg mr-4" width="1.2em" height="1.2em" viewBox="2 0 24 24"
                                    stroke-width="2.4" stroke="currentColor" fill="none" stroke-linecap="round"
                                    stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" />
                                    <rect x="5" y="3" width="14" height="18" rx="2" />
                                    <line x1="9" y1="7" x2="15" y2="7" />
                                    <line x1="9" y1="11" x2="15" y2="11" />
                                    <line x1="9" y1="15" x2="13" y2="15" />
                                </svg>
                                Notes
                            </a>
                        </li>
                        <li>
                            <a href="javascript:void(0)"
                                class="flex bg-white  {% if current == 'clubs' %}bg-blue-200 text-yellow-900{% endif %} rounded-xl font-bold text-sm py-3 px-4"">
                                <svg class="text-lg mr-4" width="1.3em" height="1.3em" viewBox="2 0 24 24"
                                    stroke-width="2.4" stroke="currentColor" fill="none" stroke-linecap="round"
                                    stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" />
                                    <line x1="12" y1="12" x2="12" y2="12.01" />
                                    <path d="M12 2a4 10 0 0 0 -4 10a4 10 0 0 0 4 10a4 10 0 0 0 4 -10a4 10 0 0 0 -4 -10"
                                        transform="rotate(45 12 12)" />
                                    <path d="M12 2a4 10 0 0 0 -4 10a4 10 0 0 0 4 10a4 10 0 0 0 4 -10a4 10 0 0 0 -4 -10"
                                        transform="rotate(-45 12 12)" />
                                </svg>
                                Clubs
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="p-4">
                <a type="button" href="{% url 'app_webapp:logout' %}"
                    class="inline-flex items-center justify-center h-9 px-4 rounded-xl bg-gray-900 text-gray-300 hover:text-white text-sm font-semibold transition">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" class=""
                        viewBox="0 0 16 16">
                        <path
                            d="M12 1a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2a1 1 0 0 1 1-1h8zm-2 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
                    </svg>
                </a>
                <a type="button" href="{% url 'app_webapp:logout' %}" class="font-bold text-sm ml-2">Logout</a>
            </div>
        </div>
    </aside>
</div>

webapp/templates/webapp/assignment.html
{% extends 'webapp/_base.html' %}
{% load extras %}
{% block title %} Assignments {% endblock title %}
{% block content %}
<div class="flex h-screen antialiased text-gray-800">
    <div class="flex flex-row h-full w-full overflow-x-hidden">
      <div class="flex flex-col py-8 pl-6 pr-2 w-64 bg-white flex-shrink-0">
        {% include "webapp/_sidebar.html" with current="assign" %}
      </div>
      <!-- talako code is for the right ko dropdown-->
      <style>
        .tab {
          overflow: hidden;
        }
        .tab-content {
          max-height: 0;
          transition: all 0.5s;
        }
        input:checked + .tab-label .test {
          background-color: #000;
        }
        input:checked + .tab-label .test svg {
          transform: rotate(180deg);
          stroke: #fff;
        }
        input:checked + .tab-label::after {
          transform: rotate(90deg);
        }
        input:checked ~ .tab-content {
          max-height: 100vh;
        }
      </style>

      <main class="w-3/5 p-8 mx-auto">
        <section class="shadow row">
          <div class="tabs">
            {% for assignment in assignments %}
            <div class="border-b tab">
              <div class="border-l-2 border-transparent relative">
                <input
                  class="w-full absolute z-10 cursor-pointer opacity-0 h-5 top-6"
                  type="checkbox"
                  id="chck1"
                />
                <header
                  class="flex justify-between items-center p-5 pl-8 pr-8 cursor-pointer select-none tab-label"
                  for="chck1"
                >
                  <span class="text-grey-darkest font-thin text-xl">
                   {{assignment.topic}}
                  </span>
                  <div
                    class="rounded-full border border-grey w-7 h-7 flex items-center justify-center test"
                  >
                    <!-- icon by feathericons.com -->
                    <svg
                      aria-hidden="true"
                      class=""
                      data-reactid="266"
                      fill="none"
                      height="24"
                      stroke="#606F7B"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      viewbox="0 0 24 24"
                      width="24"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <polyline points="6 9 12 15 18 9"></polyline>
                    </svg>
                  </div>
                </header>
                <div class="tab-content overflow-y-scroll">
                  <div class="pl-8 pr-8 pb-5 text-grey-darkest ">
                    <ul class="pl-4">
                      <li class="pb-2">
                        {{assigment.description}}
                      </li>
                    </ul>
                    <div class = "justify-around">
                      <div><label class="block mb-2 text-sm font-medium text-gray-900 dark:text-black-300 ">Status: {{user|assgmentStatus:assignment}}</label>
                      </div>
                      <a href="{% url 'app_webapp:create_assignment' assignment.id %}"><button class="bottom-2 right-10 px-3 py-1.5 bg-indigo-500 outline-none rounded text-white shadow-indigo-200 shadow-lg font-medium active:shadow-none active:scale-95 hover:bg-indigo-600 focus:bg-indigo-600 focus:ring-2 focus:ring-indigo-600 focus:ring-offset-2 disabled:bg-gray-400/80 disabled:shadow-none disabled:cursor-not-allowed transition-colors duration-200">Submit</button>
                      </a>
                    </div>
                    </div>
            
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </section>
      </main>
{% endblock content %}

webapp/templates/webapp/login.html
{% extends "webapp/_base.html" %}
{% block title %} Login {% endblock title %}
{% block content %}
<div class="flex items-center justify-center min-h-screen bg-gray-100">
    <div class="px-8 py-6 mt-4 text-left bg-white shadow-lg">
        <div class="flex justify-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-20 h-20 text-blue-600" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path d="M12 14l9-5-9-5-9 5 9 5z" />
                <path
                    d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z" />
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222" />
            </svg>
        </div>
        <h3 class="text-2xl font-bold text-center">Login to your account</h3>
        <form action="{% url 'app_webapp:login' %}" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <p class="text-xs tracking-wide text-center text-red-600">{{error}}</p>
            {% endfor %}
            <div class="mt-4">
                <div>
                    <label class="block" for="email">Email/Username<label>
                            <input type="text" name="username" placeholder="Email/Username" class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600">
                </div>
                <div class="mt-4">
                    <label class="block">Password<label>
                            <input type="password" name="password" placeholder="Password" class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600">
                </div>
                <div class="flex items-baseline justify-between">
                    <button type="submit" class="px-6 py-2 mt-4 text-white bg-blue-600 rounded-lg hover:bg-blue-900">Login</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}